# Generated by Django 2.0 on 2019-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20191223_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y%m', verbose_name='头像'),
        ),
    ]
