# Generated by Django 2.0 on 2019-12-24 17:15

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191224_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default=1, verbose_name='课程详情'),
            preserve_default=False,
        ),
    ]
